name: GitHub Pages

on:
  push:
    branches:
      - develop
  schedule:
    # Cache is invalidated after 7 days of inactivity so run every 6 days
    - cron: '6 6 */6 * *'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: '8.10.2'
          enable-stack: true
          stack-version: 'latest'
      - name: Cache ~/.stack
        uses: actions/cache@v2.1.3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - name: Install dependencies
        run: |
          stack install hakyll
          sudo apt install -y minify sassc
      - name: Build site
        run: |
          stack build
          stack exec site build
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          cname: natan.la

